name: EncompassREST Build
on:
  push:
    branches:
      - master
      - feature/*
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore NuGet Packages
      run: nuget restore src/EncompassRest.sln

    - name: Build Solution
      run: dotnet build src/EncompassRest.sln