name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - master
      - feature/*
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
      TARGET_FRAMEWORK: netstandard2.1
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/bjatchley/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore NuGet Packages
      run: dotnet restore src/EncompassRest.sln

    - name: Publish Solution
      run: dotnet publish -c $env:CONFIGURATION -f $env:TARGET_FRAMEWORK src/EncompassRest.sln

    - name: Pack Solution
      run: dotnet pack -c $env:CONFIGURATION -p:TargetFramework=$env:TARGET_FRAMEWORK src/EncompassRest.sln
