name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - master
      - feature/*
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore NuGet Packages
      run: dotnet restore src/EncompassRest.sln

    - name: Publish Solution
      run: dotnet publish -c $env:CONFIGURATION $src/EncompassRest.sln