name: Publish to NuGet
on:
  push:
    branches: 
      - master
jobs:
  publish:
    name: BuildPackPublish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PublishOnVersionChange
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/EncompassRest/EncompassRest.csproj
